remove aur packages and switch too archlinux-xdg-menu

diff --git a/airootfs/abif-master/abif b/airootfs/abif-master/abif
--- a/airootfs/abif-master/abif
+++ b/airootfs/abif-master/abif
@@ -1,6 +1,6 @@
 # !/bin/bash
 #
-# Arch Base Installation Framework (version 1.0 - 22-Sept-2015)
+# ArchBang Installation Framework (version 2.1 - 29-Sept-2015)
 #
 # Written by Carl Duff for ArchBang Linux
 #
@@ -18,8 +18,8 @@
 # ISO Specific Variables
 ISO_HOST="archbang"                           		# ISO Host Name
 ISO_USER="ablive"           						# Live user account
-VERSION="ArchBang Installation Framework 2.0"		# Installer Name / Version
-TRANS_SRC="/bin/"									# Dir where translation files are stored
+VERSION="ArchBang Installation Framework 2.1"		# Installer Name / Version
+TRANS_SRC="/abif-master/"							# Dir where translation files are stored
 
 # Create a temporary file to store menu selections
 ANSWER="/tmp/.abif"
@@ -190,7 +190,7 @@ show_devices() {
 set_keymap() { 
 	
 	KEYMAPS=""
-    for i in $(localectl --no-pager list-keymaps); do
+    for i in $(ls -R /usr/share/kbd/keymaps | grep "map.gz" | sed 's/\.map.gz//g' | sort); do
         KEYMAPS="${KEYMAPS} ${i} -"
     done
     
@@ -321,7 +321,7 @@ set_hostname() {
    HOST_NAME=$(cat ${ANSWER})
 
    echo "$HOST_NAME" > ${MOUNTPOINT}/etc/hostname
-   sed -i "s/${ISO_HOST}/${HOST_NAME}/" ${MOUNTPOINT}/etc/hosts
+   echo -e "#<ip-address>\t<hostname.domain.org>\t<hostname>\n127.0.0.1\tlocalhost.localdomain\tlocalhost\t${HOST_NAME}\n::1\tlocalhost.localdomain\tlocalhost\t${HOST_NAME}" > ${MOUNTPOINT}/etc/hosts
 }
 
 # Set the installed system's root password
@@ -386,15 +386,22 @@ create_new_user() {
         arch_chroot "passwd $ISO_USER" < /tmp/.passwd >/dev/null 2>/tmp/.errlog
         check_for_error
         
-        # Switch from ISO_USER name to entered USER name
-        sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/home/$ISO_USER/.config/obmenu-generator/config.pl
-        sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/home/$ISO_USER/.config/obmenu-generator/schema.pl
+        # Convert to entered username - configs
+        sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/home/$ISO_USER/.gtkrc-2.0
+        sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/home/$ISO_USER/.config/openbox/autostart
+        sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/root/.gtkrc-2.0
+        #sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/home/$ISO_USER/.config/obmenu-generator/config.pl
+        #sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/home/$ISO_USER/.config/obmenu-generator/schema.pl
+        
+        # Convert to entered username - group, password, folder, and ownership
         sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/etc/group 2>/tmp/.errlog
         sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/etc/gshadow 2>>/tmp/.errlog
         sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/etc/passwd 2>>/tmp/.errlog
         sed -i "s/$ISO_USER/$USER/g" ${MOUNTPOINT}/etc/shadow 2>>/tmp/.errlog
         mv ${MOUNTPOINT}/home/$ISO_USER ${MOUNTPOINT}/home/$USER 2>>/tmp/.errlog
         chown -R $USER:users ${MOUNTPOINT}/home/$USER 2>>/tmp/.errlog
+        
+        # Change sudoers file to require passwords for sudo commands
         sed -i '/%wheel ALL=(ALL) ALL/s/^#//' ${MOUNTPOINT}/etc/sudoers 2>>/tmp/.errlog
         sed -i '/%wheel ALL=(ALL) ALL NOPASSWD: ALL/s/#%wheel ALL=(ALL) ALL NOPASSWD: ALL//' ${MOUNTPOINT}/etc/sudoers 2>>/tmp/.errlog
         check_for_error
@@ -570,14 +577,32 @@ delete_partitions(){
 }
 
     dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title "$_PartToolTitle" \
-    --menu "$_PartToolBody" 0 0 6 \
+    --menu "$_PartToolBody" 0 0 7 \
     "1" $"Auto Partition" \
- 	"2" $"GParted" 2>${ANSWER}	
+ 	"2" $"GParted" \
+ 	"3" $"Parted (BIOS & UEFI)" \
+	"4" $"CFDisk (BIOS/MBR)" \
+	"5" $"CGDisk (UEFI/GPT)" \
+	"6" $"FDisk  (BIOS & UEFI)" \
+	"7" $"GDisk  (UEFI/GPT)" 2>${ANSWER}
 
     case $(cat ${ANSWER}) in
         "1") auto_partition
              ;;
-        "2") gparted ${DEVICE}
+        "2") gparted ${DEVICE} >/dev/null 2>&1
+             ;;
+        "3") clear
+             parted ${DEVICE}
+             ;;
+        "4") cfdisk ${DEVICE}
+             ;;
+        "5") cgdisk ${DEVICE}
+             ;;       
+        "6") clear
+             fdisk ${DEVICE}
+             ;;
+        "7") clear
+             gdisk ${DEVICE}
              ;;
           *) prep_menu
              ;;
@@ -1246,39 +1271,55 @@ check_lv_size() {
 
 install_root(){
 
-# mount image file
+# Mount image file
   mkdir -p $BYPASS
   mount $AIROOTIMG $BYPASS
-  
+
 # copy files from bypass to install device
   clear
   rsync -a --progress $BYPASS/ $MOUNTPOINT/ 2>/tmp/.errlog
+  #rsync -a --progress $AIROOTIMG $MOUNTPOINT/ 2>/tmp/.errlog
   check_for_error
   umount -l $BYPASS
-# remove abinstall from openbox menu
-  sed -i '/abinstall/,+3d' $MOUNTPOINT/home/ablive/.config/obmenu-generator/schema.pl
-# set xkeyboard map
-  sed -i "s/us/${KEYMAP_XKB:0:2}/g" $MOUNTPOINT/etc/X11/xorg.conf.d/01-keyboard-layout.conf
+# Change openbox menu and oblogout
+  cp -f /inst/menu.xml $MOUNTPOINT/home/ablive/.config/openbox/menu.xml
+  cp -f /inst/oblogout.conf $MOUNTPOINT/etc/oblogout.conf
+  
+# Keyboard config for vc and x11
+  [[ -e /tmp/vconsole.conf ]] && cp /tmp/vconsole.conf ${MOUNTPOINT}/etc/vconsole.conf 2>>/tmp/.errlog
+  [[ -e /tmp/01-keyboard-layout.conf ]] && cp -f /tmp/01-keyboard-layout.conf ${MOUNTPOINT}/etc/X11/xorg.conf.d/$(ls ${MOUNTPOINT}/etc/X11/xorg.conf.d/ | grep "keyboard") 2>>/tmp/.errlog
+  check_for_error
+  
 # set up kernel for mkiniticpio
   cp /run/archiso/bootmnt/arch/boot/${ARCHI}/vmlinuz ${MOUNTPOINT}/boot/vmlinuz-linux
-# put live driver into new install
-  cp /etc/X11/xorg.conf.d/20-gpudriver.conf ${MOUNTPOINT}/etc/X11/xorg.conf.d/20-gpudriver.conf &>/dev/null
+
 # copy over new mirrorlist
   cp /etc/pacman.d/mirrorlist ${MOUNTPOINT}/etc/pacman.d/mirrorlist
-# Clean up new install
-  rm -f ${MOUNTPOINT}/usr/bin/abinstall &> /dev/null
+  
+# Clean up installation
+  [[ -d ${MOUNTPOINT}/abif-master ]] && rm -R ${MOUNTPOINT}/abif-master &> /dev/null
+  [[ -d ${MOUNTPOINT}/aif-master ]] && rm -R ${MOUNTPOINT}/abif-master &> /dev/null
+  [[ -d ${MOUNTPOINT}/inst ]] && rm -R ${MOUNTPOINT}/inst &> /dev/null
+  rm -R ${MOUNTPOINT}/etc/systemd/system/getty@tty1.service.d
+  rm -f ${MOUNTPOINT}/usr/bin/lastmin &> /dev/null
   rm -rf ${MOUNTPOINT}/vomi &> /dev/null
   rm -rf ${BYPASS} &> /dev/null
   rm -rf ${MOUNTPOINT}/source &> /dev/null
+  rm -rf ${MOUNTPOINT}/src &> /dev/null
   rmdir ${MOUNTPOINT}/bypass &> /dev/null
   rmdir ${MOUNTPOINT}/src &> /dev/null
   rmdir ${MOUNTPOINT}/source &> /dev/null
+  rm -f ${MOUNTPOINT}/etc/sudoers.d/g_wheel
+  rm -f ${MOUNTPOINT}/var/lib/NetworkManager/NetworkManager.state
+
  
 # clean out archiso files from install
   find ${MOUNTPOINT}/usr/lib/initcpio -name archiso* -type f -exec rm '{}' \;
  
 # systemd
   rm ${MOUNTPOINT}/etc/systemd/system/default.target &> /dev/null
+  arch_chroot  "/usr/bin/systemctl -f disable lastmin.service || true"
+  rm -f ${MOUNTPOINT}/usr/bin/lastmin &> /dev/null
 
 # Journal 
   sed -i 's/volatile/auto/g' ${MOUNTPOINT}/etc/systemd/journald.conf
@@ -1288,7 +1329,7 @@ install_root(){
   arch_chroot "/usr/bin/touch /var/lib/pacman/sync/{core.db,extra.db,community.db}"
 
 # Fix NetworkManager
-arch_chroot "systemctl enable NetworkManager -f"
+  arch_chroot "systemctl enable NetworkManager -f"
 
 # Keyboard config for vc and x11
   [[ -e /tmp/vconsole.conf ]] && cp /tmp/vconsole.conf ${MOUNTPOINT}/etc/vconsole.conf 2>>/tmp/.errlog
@@ -1613,7 +1654,7 @@ edit_configs() {
 	   fi
 	fi
 
-   dialog --default-item ${HIGHLIGHT_SUB} --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title "$_SeeConfOptTitle" --menu "$_SeeConfOptBody" 0 0 12 \
+   dialog --default-item ${HIGHLIGHT_SUB} --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title "$_SeeConfOptTitle" --menu "$_SeeConfOptBody" 0 0 11 \
    "1" "/etc/vconsole.conf" \
    "2" "/etc/locale.conf" \
    "3" "/etc/hostname" \
@@ -1622,10 +1663,9 @@ edit_configs() {
    "6" "/etc/mkinitcpio.conf" \
    "7" "/etc/fstab" \
    "8" "$BOOTLOADER" \
-   "9" "/etc/lxdm/lxdm.conf" \
-  "10" "/etc/pacman.conf" \
-  "11" "/etc/pacman.d/mirrorlist" \
-  "12" "$_Back" 2>${ANSWER}
+   "9" "/etc/pacman.conf" \
+  "10" "/etc/pacman.d/mirrorlist" \
+  "11" "$_Back" 2>${ANSWER}
 	
 	HIGHLIGHT_SUB=$(cat ${ANSWER})
 	case $(cat ${ANSWER}) in
@@ -1657,14 +1697,9 @@ edit_configs() {
                            ;;
               esac
              ;;
-        "9") FILE="${MOUNTPOINT}/etc/lxdm/lxdm.conf" 
-             #FILE="${MOUNTPOINT}/etc/lightdm/lightdm.conf" 
-             #FILE="${MOUNTPOINT}/etc/sddm.conf"
-             #FILE="${MOUNTPOINT}/etc/slim.conf"
-             ;;  
-       "10") FILE="${MOUNTPOINT}/etc/pacman.conf"
+        "9") FILE="${MOUNTPOINT}/etc/pacman.conf"
              ;;
-       "11") FILE="${MOUNTPOINT}/etc/pacman.d/mirrorlist"
+       "10") FILE="${MOUNTPOINT}/etc/pacman.d/mirrorlist"
              ;;   
          *) main_menu
             ;;
